### ISSUE TITLE
GVLE18_01a could not provide a CC process for nue+37Cl   v3.04

### ISSUE THREAD

**Issue by WentaiLuo** [GENIE-MC/Generator#328]
Hello,
The Genie version I am using is 3.04 and the model used is GVLE18_01a with an energy interval of 0.001-0.6 GeV

When generating the cross section of nue with Cl37, the common CC process (nue+37Cl->e-+37Ar) is not present in the cross section data, and the same problem occurs between nue and 7Li. Is it my mistake or some other problem?
Command line:

gmkspl -p 12 -t 1000170370 -n 600 -e 0.6 --tune GVLE18_01a_00_000 -o 1000170370_12_GVLE18_01a.xml

Looking forward to your answer!

![屏幕截图 2023-09-20 195310](https://github.com/GENIE-MC/Generator/assets/61787337/40286fbb-50e8-490f-91a0-416a1b1570fd)

**Comment by WentaiLuo** [comment]
What's more, the IBD spline is empty

**Comment by candreop** [comment]
Hi Wentai. The low energy (LE) generators in GENIE are not as well developed as the medium (ME) and high-energy (HE) ones, and there is a limit in what you can do. If you want to use the LE generators in an expriment where the dominant process is IBD or CEvNS, then they are fine. The nuclear process you're mentioning is not simulated, except (very partially) for O16 (installed several years ago by someone looking to simulate a water target). Having said that, if what you want is to simulate events at 600 MeV (as I see above) perhaps the ME generators are much more suitable for you? Of course the ME generators include nuclear CCEQ and NCEL (amongst many other processes), and it should be possible to extrapolate these down to much lower energy (albeit with limited validity due to the treatment of nuclear effects). But, to first order, you should be able to use the ME generator even down to 100 MeV or so. Hope this helps.

**Comment by WentaiLuo** [comment]
> Hi Wentai. The low energy (LE) generators in GENIE are not as well developed as the medium (ME) and high-energy (HE) ones, and there is a limit in what you can do. If you want to use the LE generators in an expriment where the dominant process is IBD or CEvNS, then they are fine. The nuclear process you're mentioning is not simulated, except (very partially) for O16 (installed several years ago by someone looking to simulate a water target). Having said that, if what you want is to simulate events at 600 MeV (as I see above) perhaps the ME generators are much more suitable for you? Of course the ME generators include nuclear CCQE and NCEL processes (amongst many other processes), and it should be possible to extrapolate these down to much lower energy (albeit with limited validity due to the treatment of nuclear effects). But, to first order, you should be able to use the ME generator even down to 100 MeV or so. Hope this helps.
> What exactly are you trying to do?

Sorry brother, I've been busy with wedding photos for the past few days so I've only replied today.  What I would like to do is to look for potential events of deposition energies of 10-30 MeV, where reactions of high energy neutrinos with different nuclides are included. The nuclides used are 7Li 6Li 37Cl 35Cl 1H 2H 16O 18O, six flavors with neutrino energies in the range of 0-10 GeV. Since this is my first time using Genie, I want to verify the plausibility of the individual software packages before formally generating the end-state particles. Previously my research has covered energy regions less than 10 MeV, so I was familiar with this energy region and wanted to verify it as such. In using it I realized that IBD reactions are not provided in ME's model, while IBD is in LE, so I wanted to verify the reasonableness of LE. However, the energy region of LE goes up to 600 MeV, so I still need the help of ME. Now I'm a bit confused as to what to choose between LE and ME, as the energy regions used and the reaction processes included are quite different. Do you have any better advice?
