### ISSUE TITLE
1569297196 WARN XSecSplLst : [s] <SplineExists (110)> : No splines for tune G18_02a_00_000 were found!

### ISSUE THREAD

**Issue by MiriamaRajao** [GENIE-MC/Generator#61]
Hello,

I was just intalling GENIE on my computer and I wanted to try if everything were installed properly so I tried generating some basic events. I did not put in any specific cross section files. However I kept getting the error : 

1569297196 WARN XSecSplLst : [s] <SplineExists (110)> : No splines for tune G18_02a_00_000 were found!

And it went into a sort of infinite loop where it keeps repeating the same error. So I wanted to ask please if that is an error coming from the fact I did not specify any cross section spline or if it is a problem coming from the installation.

Thank you very much!

**Comment by nusense** [comment]
Miriama,
   In order to do event generation efficiently, GENIE will want appropriate tune-specific spline files with pre-computed cross sections for subprocesses as a function of energy.  In some cases, if these are not supplied, GENIE will attempt to generate them on the fly -- but this can be a very computationally expensive operation so it could look like things were in an infinite loop.

You can download a variety of spline sets from:  https://scisoft.fnal.gov/scisoft/packages/genie_xsec/

Depending on your specific needs this might be sufficient.

**Comment by MiriamaRajao** [comment]
Thank you very much for the your help and the spline sets!
